version: '2'
services:
  db:
    build: ./db
    container_name: mysql-profesia
    command: --default-authentication-plugin=mysql_native_password
    environment:
       MYSQL_ROOT_PASSWORD: profesia
       MYSQL_DATABASE: profesia
       MYSQL_USER: profesia
       MYSQL_PASSWORD: profesia123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
    db_data: {}